config/routes.rb
Blog::Application.routes.draw do
  resources :ideas do
    get 'getkey', :on => :member 
  end

  match 'idea/getkey/:idea_id', :controller => 'ideas', :action => 'getkey'

  resources :posts
  
  root :to => 'ideas#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  attr_accessible :description, :name, :picture, :keyword1, :score1, :keyword2, :score2

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      #format.html { redirect_to action: "getkey", id: @idea.id }
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        #format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.html { redirect_to action: "getkey", id: @idea.id }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  # GET /ideas/getKey/1
  def getkey
    require './alchemyapi'
    alchemyapi = AlchemyAPI.new()

    @idea = Idea.find(params[:id])

    image_file = File.binread("public#{@idea.picture_url}")
    response = alchemyapi.image_tag('image', '', { 'imagePostMode'=>'raw'}, image_file)

    puts '###### result from alchemyapi ######'
    puts response['status']
    puts ''
    if response.key?('imageKeywords')
        puts 'Keywords:'
        @i = 1
        for keyword in response['imageKeywords']
            puts "\ttext: " + keyword['text']
            puts "\tscore: " + keyword['score']
            if @i == 1 
                @idea.attributes = ({ :keyword1 => keyword['text'], :score1 => keyword['score'] })
            end
            if @i == 2 
                @idea.attributes = ({ :keyword2 => keyword['text'], :score2 => keyword['score'] })
            end
            @i += 1
        end
        @idea.save
    end
    puts '####################################'
    puts ''
    
    
    respond_to do |format|
      format.html # getkey.html.erb
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="wrapper">
      <%= f.file_field :picture, {:class => "big"} %>
    </div>
    <button type="button" class="btn btn-info">Browse...</button>
  </div>
  <div class="actions">
      <%= f.submit 'Submit', :class => "btn btn-default" %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/getkey.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-12">
<p>
<%= image_tag(@idea.picture_url, :width => 400, :class => "img-rounded center-block", :alt => "Cinque Terre") if @idea.picture.present? %>
</p>
</ br>
</div>

<div class="col-md-12 set-center">
<% unless @idea.keyword1.nil? %>
<h1 class="center-block">Is it a <%= @idea.keyword1 %> ?</h1>
<h4 class="center-block">We are <%= @idea.score1 %> sure.</h3>
<% end %>
<% unless @idea.keyword2.nil? %>
<h2 class="center-block">Or is it a <%= @idea.keyword2 %> ?</h1>
<h4 class="center-block">We are <%= @idea.score2 %> sure.</h3>
<% end %>
<% if @idea.keyword1.nil? and @idea.keyword2.nil? %>
<h2 class="center-block">Hmm...we don't know what it is...</h1>
<% end %>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>
</div>

app/views/ideas/index.html.erb
<div class="container">
<h1>Upload an image, and Alchemy will guess what it is</h1>
</ br>
<h4 >Click <mark>"GetKey"</mark></h3>
</ br>
<p class="bg-info"> It takes a while when click on "GetKey" (Depends on img size).</p>
</div>

<div class="container">
  <table class="table table-hover">
    <thead>      
      <tr>
        <th>Picture</th>
        <th>Keywork1</th>
        <th>Score1</th>
        <th>Keyword2</th>
        <th>Score2</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.picture %></td>
        <td><%= idea.keyword1 %></td>
        <td><%= idea.score1 %></td>
        <td><%= idea.keyword2 %></td>
        <td><%= idea.score2 %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'GetKey', getkey_idea_path(idea) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br />

<%= link_to 'New Image', new_idea_path, :class => "btn btn-warning" %>

app/views/ideas/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%= image_tag(@idea.picture_url, :width => 400, :class => "img-rounded center-block", :alt => "Cinque Terre") if @idea.picture.present? %>
</ br>
</p>

<div class="col-md-12 set-center">
<% unless @idea.keyword1.nil? %>
<h1 class="center-block">Is it a <%= @idea.keyword1 %> ?</h1>
<h4 class="center-block">We are <%= @idea.score1 %> sure.</h3>
<% end %>
<% unless @idea.keyword2.nil? %>
<h2 class="center-block">Or is it a <%= @idea.keyword2 %> ?</h1>
<h4 class="center-block">We are <%= @idea.score2 %> sure.</h3>
<% end %>
<% if @idea.keyword1.nil? and @idea.keyword2.nil? %>
<h2 class="center-block">Hmm...we don't know what it is...</h1>
<% end %>


<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alchemy on Bluemix</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container">
  <div class="navbar-header">
    <a class="navbar-brand" href="/">Alchemy on Bluemix</a>
  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="/ideas">Images</a></li>
    </ul>
  </div>
</div>
</nav>
<div class="container">
<%= yield %>
</div>

<div class="container bottom-block">
</div>

<div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
      <p class="navbar-text pull-left">This project is built by IBM Taiwan interns. 2015/08</p>
      <a href="http://www.alchemyapi.com/" class="navbar-btn btn-warning btn pull-right">Alchemy</a>
      <a href="https://console.ng.bluemix.net/" class="navbar-btn btn-info btn pull-right">Bluemix</a>
  </div>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<article>
<h1>Editing post</h1>

<%= render 'form' %>

<ul class="postmenu">
   <li><%= link_to 'Show', @post %><li>
   <li><%= link_to 'Back', "/" %></li>
</ul>

</article>

app/views/posts/index.html.erb
<h1>posts___</h1>

<% @posts.each do |post| %>
    <div class="minipost">
    <h3><%= post.title %></h3><p class="date"><%= post.created_at.to_s(:postdate) %></p><br>
    <p><%= truncate(post.body, length: 300) %></p><br>
    <ul class="postmenu">    
       <li><%= link_to 'Read More', post %></li>
       <li><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?'} %></li>       
    </ul>
    </div>

  
<% end %>

<div style="clear: both;"></div>

<%= link_to 'NEW POST', new_post_path, { :class => "button"} %><br>

app/views/posts/new.html.erb
<article>
<h1>New post</h1>

<%= render 'form' %>

<ul class="postmenu">
   <li><%= link_to 'Back', "/" %></li>
</ul>

</article>

app/views/posts/show.html.erb
<article>

 <h3><%= @post.title %></h3><p class="date"><%= @post.created_at.to_s(:postdate) %></p><br>

<p><%= @post.body %></p>

<ul class="postmenu">
  <li><%= link_to 'Edit', edit_post_path(@post) %></li>  
  <li><%= link_to 'Back', "/" %></li>
</ul>

</article>